# Generated by Django 4.0.6 on 2022-09-11 10:36

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_avatar_alter_user_groups_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(upload_to=accounts.models.user_avatar),
        ),
    ]
