version: "3"

services:

  backend:
    image: local:0.0.1
    build: .
    container_name: backend
    stdin_open: true
    tty: true
    env_file:
      - .env

    ports:
      - "8000:8000"

  memcached:
    image: memcached:1.6.17
    container_name: memcached
    ports:
      - "11211:11211"

  rabbitmq:
    image: rabbitmq:3.11.2-management
    container_name: rabbitmq
    ports:
      - "5672:5672"

  postgres:
    image: postgres:15.0-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf:ro"

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin@admin.com
    ports:
      - "5050:80"

  celery:
    image: local:0.0.1
    build: .
    container_name: celery
    stdin_open: true
    tty: true
    env_file:
      - .env
    command:
      celery -A settings worker --loglevel=INFO --pidfile=/tmp/celery.pid

  celerybeat:
    image: local:0.0.1
    build: .
    container_name: celerybeat
    stdin_open: true
    tty: true
    env_file:
      - .env
    command:
      celery -A settings beat --loglevel=INFO --schedule=/tmp/celerybeat-schedule --pidfile=/tmp/celerybeat.pid

  celeryflower:
    image: local:0.0.1
    build: .
    container_name: celeryflower
    stdin_open: true
    tty: true
    env_file:
      - .env
    ports:
      - "5555:5555"
    command: celery -A settings flower --address=0.0.0.0 --port=5555




volumes:
  db_data: {}




