# Generated by Django 4.0.6 on 2022-07-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_to', models.EmailField(max_length=254)),
                ('email_from', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('massage', models.CharField(max_length=500)),
            ],
        ),
    ]
