# Generated by Django 4.0.6 on 2022-08-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_time', models.CharField(max_length=64)),
                ('request_method', models.CharField(max_length=64)),
                ('query_params', models.CharField(max_length=64)),
                ('ip', models.CharField(max_length=64)),
                ('path', models.CharField(max_length=64)),
            ],
        ),
    ]
