# Generated by Django 4.0.6 on 2022-08-28 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_responselog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='source',
        ),
    ]
