# Generated by Django 4.0.6 on 2022-09-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0007_alter_rate_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='logo',
            field=models.FileField(default='av.png', upload_to=''),
        ),
    ]
