# Generated by Django 4.0.6 on 2022-10-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0008_source_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='created',
            field=models.CharField(default='29.10.2022', max_length=30),
        ),
    ]
